global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Alertmanager'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['greenhouse-pi.local:8000']
      labels:
        group: 'environment'
        location: 'Darien'

  - job_name: 'nodeexp'
    static_configs:
      - targets: ['nodeexp:9100']
