{
 "title": "Environment",
 "description": "Pimoroni Enviroplus dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "location", "label": "location", "query": { "query": "temperature" } }
  ]
 },
 "panels": [
  { "title": "Current measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(temperature{group=\"environment\", location=~\"[[location]]\"} * 1.8) + 32",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pressure{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Particles",
   "type": "stat",
   "description": "PM1.0 ug/m3 (ultrafine particles)\nPM2.5 ug/m3 (combustion particles, organic compounds, metals)\nPM10 ug/m3  (dust, pollen, mould spores)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PM1{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pm1_{{location}} (ultrafine particles)"
    },
    {
     "expr": "PM25{group=\"environment\", location=~\"[[location]]\"} - PM1{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pm2.5_{{location}} (combustion particles, organic compounds, metals)"
    },
    {
     "expr": "PM10{group=\"environment\", location=~\"Vught\"} - PM25{group=\"environment\", location=~\"Vught\"}",
     "legendFormat": "pm10_{{location}} (dust, pollen, mould spores)"
    }
   ]
  },
  { "title": "Historical measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "temperature{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "temperature_raw_{{location}}"
    },
    {
     "expr": "avg_over_time(temperature{group=\"environment\", location=~\"[[location]]\"}[15m])",
     "legendFormat": "temperature_smooth_{{location}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "pressure{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pressure_{{location}}"
    }
   ]
  },
  {
   "title": "Particles",
   "type": "graph",
   "description": "PM1.0 ug/m3 (ultrafine particles)\nPM2.5 ug/m3 (combustion particles, organic compounds, metals)\nPM10 ug/m3  (dust, pollen, mould spores)",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "expr": "PM1{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pm1_{{location}} (ultrafine particles)"
    },
    {
     "expr": "PM25{group=\"environment\", location=~\"[[location]]\"} - PM1{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pm2.5_{{location}} (combustion particles, organic compounds, metals)"
    },
    {
     "expr": "PM10{group=\"environment\", location=~\"[[location]]\"} - PM25{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "pm10_{{location}} (dust, pollen, mould spores)"
    }
   ]
  },
  {
   "title": "Gas (NH3, Oxidising, Reducing)",
   "type": "graph",
   "description": "NH3 -> Ammonia, \nOxidising -> Nitrogen Dioxide,\nReducing -> Carbon Monoxide",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ohm" }
   ],
   "targets": [
    {
     "expr": "NH3{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "nh3_{{location}}"
    },
    {
     "expr": "oxidising{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "oxidising_{{location}}"
    },
    {
     "expr": "reducing{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "reducing_{{location}}"
    }
   ]
  },
  {
   "title": "Proximity",
   "type": "graph",
   "description": "A value (from zero to a couple of thousand) for the proximity, with larger numbers being closer proximity and vice versa.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "proximity{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "proximity_{{location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "humidity{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "humidity_{{location}}"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "description": "A value (from zero to a couple of thousand) for the proximity, with larger numbers being closer proximity and vice versa.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "lux{group=\"environment\", location=~\"[[location]]\"}",
     "legendFormat": "lux_{{location}}"
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM1 - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "rate(pm1_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "PM2.5 - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "rate(pm25_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "PM10 - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "rate(pm10_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gasses - Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oxidising - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(oxidising_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Reducing - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
     "targets": [
      {
       "expr": "rate(reducing_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NH3 - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
     "targets": [
      {
       "expr": "rate(nh3_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}